# Generated by Django 3.1.4 on 2021-01-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='time',
            new_name='date',
        ),
    ]
