# Generated by Django 3.1.4 on 2021-01-20 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_aboutme_contactme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='img',
            new_name='photo',
        ),
    ]
