# Generated by Django 3.1.4 on 2021-01-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210120_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='last_name',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
